name: daily
description: "Flutter todo list app"

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.19.0
  logger: ^2.3.0
  cupertino_icons: ^1.0.8
  uuid: ^4.4.0
  provider: ^6.1.2
  json_annotation: ^4.9.0
  dio: ^5.4.3+1
  retrofit: ^4.1.0
  sqflite: ^2.3.3+1
  get_it: ^7.7.0
  shared_preferences: ^2.2.3
  go_router: ^14.2.0
  equatable: ^2.0.5
  freezed_annotation: ^2.4.4
  firebase_core: ^3.2.0
  firebase_analytics: ^11.2.0
  firebase_crashlytics: ^4.0.3
  firebase_remote_config: ^5.0.3

dev_dependencies:

  flutter_test:
    sdk: flutter

  integration_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.11
  retrofit_generator: ^8.1.0
  mocktail: ^1.0.4
  freezed: ^2.5.2



flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.webp"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
