name: daily
description: "Flutter todo list app"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  logger: ^2.3.0

  cupertino_icons: ^1.0.8
  uuid: ^4.4.0
  provider: ^6.1.2


dev_dependencies:

  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^4.0.0

flutter_icons:

  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.webp"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
  generate: true