name: Flutter CI

on:
  push:
    branches: [ "main", "fourth_work_linus_torvalds" ]
  pull_request:
    branches: [ "main", "fourth_work_linus_torvalds" ]

jobs:
  flt:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Verify formatting
        run: dart format --output=none

      - name: Run linter
        run: flutter analyze
        continue-on-error: true

      - name: Run state tests
        run: flutter test test/features/home/provider_notifiers/task_list_notifier.dart
        continue-on-error: true

      - name: Remote source test
        run: flutter test test/data/data_sources/remote/api/api_task_remote_source.dart
        continue-on-error: true

      - name: Repository test
        run: flutter test test/data/data_repository/task_data_repository.dart
        continue-on-error: true

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build apk
        env:
          ENVIRONMENT_VARIABLES: ${{ secrets.ENVIRONMENT_VARIABLES }}
        run: flutter build apk "$ENVIRONMENT_VARIABLES"

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Upload apk to Firebase distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: Testers
          file: build/app/outputs/flutter-apk/app-release.apk
